// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mSMs7FqGjFMPgGjdzmbmrV
// Component: LvBVLEU_9e
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_venturemark.module.css"; // plasmic-import: mSMs7FqGjFMPgGjdzmbmrV/projectcss
import sty from "./PlasmicLoginEmail.module.css"; // plasmic-import: LvBVLEU_9e/css

export const PlasmicLoginEmail__VariantProps = new Array();

export const PlasmicLoginEmail__ArgProps = new Array();

function PlasmicLoginEmail__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <input
      data-plasmic-name={"loginEmail"}
      data-plasmic-override={overrides.loginEmail}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.input,
        projectcss.root_reset,
        sty.loginEmail
      )}
      placeholder={"Email Address"}
      size={1}
      type={"text"}
    />
  );
}

const PlasmicDescendants = {
  loginEmail: ["loginEmail"],
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLoginEmail__ArgProps,
      internalVariantPropNames: PlasmicLoginEmail__VariantProps,
    });

    return PlasmicLoginEmail__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "loginEmail") {
    func.displayName = "PlasmicLoginEmail";
  } else {
    func.displayName = `PlasmicLoginEmail.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginEmail = Object.assign(
  // Top-level PlasmicLoginEmail renders the root element
  makeNodeComponent("loginEmail"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicLoginEmail
    internalVariantProps: PlasmicLoginEmail__VariantProps,
    internalArgProps: PlasmicLoginEmail__ArgProps,
  }
);

export default PlasmicLoginEmail;
/* prettier-ignore-end */
