// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mSMs7FqGjFMPgGjdzmbmrV
// Component: OiJWpbT5JY
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_venturemark.module.css"; // plasmic-import: mSMs7FqGjFMPgGjdzmbmrV/projectcss
import sty from "./PlasmicUpdateTitleInput.module.css"; // plasmic-import: OiJWpbT5JY/css

export const PlasmicUpdateTitleInput__VariantProps = new Array();

export const PlasmicUpdateTitleInput__ArgProps = new Array();

function PlasmicUpdateTitleInput__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <input
      data-plasmic-name={"titleInput"}
      data-plasmic-override={overrides.titleInput}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.input,
        projectcss.root_reset,
        sty.titleInput
      )}
      placeholder={"Enter a title..."}
      size={1}
      tabIndex={1}
      type={"text"}
    />
  );
}

const PlasmicDescendants = {
  titleInput: ["titleInput"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicUpdateTitleInput__ArgProps,
      internalVariantPropNames: PlasmicUpdateTitleInput__VariantProps
    });

    return PlasmicUpdateTitleInput__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "titleInput") {
    func.displayName = "PlasmicUpdateTitleInput";
  } else {
    func.displayName = `PlasmicUpdateTitleInput.${nodeName}`;
  }
  return func;
}

export const PlasmicUpdateTitleInput = Object.assign(
  // Top-level PlasmicUpdateTitleInput renders the root element
  makeNodeComponent("titleInput"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicUpdateTitleInput
    internalVariantProps: PlasmicUpdateTitleInput__VariantProps,
    internalArgProps: PlasmicUpdateTitleInput__ArgProps
  }
);

export default PlasmicUpdateTitleInput;
/* prettier-ignore-end */
