// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mSMs7FqGjFMPgGjdzmbmrV
// Component: DNixxyP8rW
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import projectcss from "./plasmic_venturemark.module.css"; // plasmic-import: mSMs7FqGjFMPgGjdzmbmrV/projectcss
import sty from "./PlasmicUpdateTitleInputShim.module.css"; // plasmic-import: DNixxyP8rW/css

export const PlasmicUpdateTitleInputShim__VariantProps = new Array();

export const PlasmicUpdateTitleInputShim__ArgProps = new Array();

function PlasmicUpdateTitleInputShim__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"updateTitle"}
      data-plasmic-override={overrides.updateTitle}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        defaultcss.__wab_text,
        projectcss.root_reset,
        sty.updateTitle
      )}
    >
      {"Choose a title for your update"}
    </div>
  );
}

const PlasmicDescendants = {
  updateTitle: ["updateTitle"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicUpdateTitleInputShim__ArgProps,
      internalVariantPropNames: PlasmicUpdateTitleInputShim__VariantProps
    });

    return PlasmicUpdateTitleInputShim__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "updateTitle") {
    func.displayName = "PlasmicUpdateTitleInputShim";
  } else {
    func.displayName = `PlasmicUpdateTitleInputShim.${nodeName}`;
  }
  return func;
}

export const PlasmicUpdateTitleInputShim = Object.assign(
  // Top-level PlasmicUpdateTitleInputShim renders the root element
  makeNodeComponent("updateTitle"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicUpdateTitleInputShim
    internalVariantProps: PlasmicUpdateTitleInputShim__VariantProps,
    internalArgProps: PlasmicUpdateTitleInputShim__ArgProps
  }
);

export default PlasmicUpdateTitleInputShim;
/* prettier-ignore-end */
