// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mTVXT6w3HHjZ4d74q3gB76
// Component: D8Y_2wee1o
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import PhotoAvatar from "../../PhotoAvatar"; // plasmic-import: uaoIqTcPRC-/component
import IconButton from "../../IconButton"; // plasmic-import: UIpuE7M1YY/component
import ListItem from "../../ListItem"; // plasmic-import: q8aEgDsN8_/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_shared.module.css"; // plasmic-import: mTVXT6w3HHjZ4d74q3gB76/projectcss
import sty from "./PlasmicMemberItem.module.css"; // plasmic-import: D8Y_2wee1o/css

import IconAdminIcon from "./icons/PlasmicIcon__IconAdmin"; // plasmic-import: 20h2nOVM8/icon
import IconDotMenuIcon from "./icons/PlasmicIcon__IconDotMenu"; // plasmic-import: Dz069s-rE/icon

export type PlasmicMemberItem__VariantMembers = {
  ventureTimeline: "isTimeline";
  userVariant: "isAdmin" | "isRequested" | "isMember" | "isSelf";
  isOwner: "isOwner";
  isDropdown: "isDropdown";
};

export type PlasmicMemberItem__VariantsArgs = {
  ventureTimeline?: SingleChoiceArg<"isTimeline">;
  userVariant?: SingleChoiceArg<
    "isAdmin" | "isRequested" | "isMember" | "isSelf"
  >;
  isOwner?: SingleBooleanChoiceArg<"isOwner">;
  isDropdown?: SingleBooleanChoiceArg<"isDropdown">;
};

type VariantPropType = keyof PlasmicMemberItem__VariantsArgs;
export const PlasmicMemberItem__VariantProps = new Array<VariantPropType>(
  "ventureTimeline",
  "userVariant",
  "isOwner",
  "isDropdown"
);

export type PlasmicMemberItem__ArgsType = {
  userName?: React.ReactNode;
  slot3?: React.ReactNode;
};

type ArgPropType = keyof PlasmicMemberItem__ArgsType;
export const PlasmicMemberItem__ArgProps = new Array<ArgPropType>(
  "userName",
  "slot3"
);

export type PlasmicMemberItem__OverridesType = {
  root?: p.Flex<"div">;
  photoAvatar?: p.Flex<typeof PhotoAvatar>;
  userInitials?: p.Flex<"div">;
  iconButton?: p.Flex<typeof IconButton>;
  dropdown?: p.Flex<"div">;
  removeInvitation?: p.Flex<typeof ListItem>;
};

export interface DefaultMemberItemProps {
  userName?: React.ReactNode;
  slot3?: React.ReactNode;
  ventureTimeline?: SingleChoiceArg<"isTimeline">;
  userVariant?: SingleChoiceArg<
    "isAdmin" | "isRequested" | "isMember" | "isSelf"
  >;
  isOwner?: SingleBooleanChoiceArg<"isOwner">;
  isDropdown?: SingleBooleanChoiceArg<"isDropdown">;
  className?: string;
}

export const defaultMemberItem__Args: Partial<PlasmicMemberItem__ArgsType> = {};

function PlasmicMemberItem__RenderFunc(props: {
  variants: PlasmicMemberItem__VariantsArgs;
  args: PlasmicMemberItem__ArgsType;
  overrides: PlasmicMemberItem__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultMemberItem__Args, props.args);
  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootisDropdown]: hasVariant(
            variants,
            "isDropdown",
            "isDropdown"
          ),
          [sty.rootisDropdown_userVariant_isRequested_isOwner]:
            hasVariant(variants, "isOwner", "isOwner") &&
            hasVariant(variants, "isDropdown", "isDropdown") &&
            hasVariant(variants, "userVariant", "isRequested"),
          [sty.rootisOwner]: hasVariant(variants, "isOwner", "isOwner"),
          [sty.rootuserVariant_isAdmin]: hasVariant(
            variants,
            "userVariant",
            "isAdmin"
          ),
          [sty.rootuserVariant_isAdmin_isDropdown_isOwner]:
            hasVariant(variants, "isOwner", "isOwner") &&
            hasVariant(variants, "userVariant", "isAdmin") &&
            hasVariant(variants, "isDropdown", "isDropdown"),
          [sty.rootuserVariant_isAdmin_isOwner]:
            hasVariant(variants, "isOwner", "isOwner") &&
            hasVariant(variants, "userVariant", "isAdmin"),
          [sty.rootuserVariant_isMember]: hasVariant(
            variants,
            "userVariant",
            "isMember"
          ),
          [sty.rootuserVariant_isMember_isDropdown_isOwner]:
            hasVariant(variants, "isOwner", "isOwner") &&
            hasVariant(variants, "isDropdown", "isDropdown") &&
            hasVariant(variants, "userVariant", "isMember"),
          [sty.rootuserVariant_isMember_isOwner]:
            hasVariant(variants, "isOwner", "isOwner") &&
            hasVariant(variants, "userVariant", "isMember"),
          [sty.rootuserVariant_isRequested]: hasVariant(
            variants,
            "userVariant",
            "isRequested"
          ),
          [sty.rootuserVariant_isRequested_isOwner]:
            hasVariant(variants, "userVariant", "isRequested") &&
            hasVariant(variants, "isOwner", "isOwner"),
          [sty.rootuserVariant_isSelf]: hasVariant(
            variants,
            "userVariant",
            "isSelf"
          ),
          [sty.rootuserVariant_isSelf_isOwner]:
            hasVariant(variants, "userVariant", "isSelf") &&
            hasVariant(variants, "isOwner", "isOwner"),
        }
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__vAfXq, {
          [sty.freeBoxuserVariant_isMember_isOwner__vAfXqGdyZrPkRzz]:
            hasVariant(variants, "isOwner", "isOwner") &&
            hasVariant(variants, "userVariant", "isMember"),
        })}
      >
        <PhotoAvatar
          data-plasmic-name={"photoAvatar"}
          data-plasmic-override={overrides.photoAvatar}
          className={classNames("__wab_instance", sty.photoAvatar, {
            [sty.photoAvataruserVariant_isRequested]: hasVariant(
              variants,
              "userVariant",
              "isRequested"
            ),
          })}
          userInitials={
            <div
              data-plasmic-name={"userInitials"}
              data-plasmic-override={overrides.userInitials}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.userInitials,
                {
                  [sty.userInitialsuserVariant_isRequested]: hasVariant(
                    variants,
                    "userVariant",
                    "isRequested"
                  ),
                }
              )}
            >
              {"KO"}
            </div>
          }
        />

        {p.renderPlasmicSlot({
          defaultContents: "User Name",
          value: args.userName,
        })}

        {false ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__biq75,
              {
                [sty.textuserVariant_isRequested__biq75OSddm]: hasVariant(
                  variants,
                  "userVariant",
                  "isRequested"
                ),
                [sty.textuserVariant_isSelf__biq75AAx2Z]: hasVariant(
                  variants,
                  "userVariant",
                  "isSelf"
                ),
              }
            )}
          >
            {"-"}
          </div>
        ) : null}
        {false
          ? p.renderPlasmicSlot({
              defaultContents: "example@email.com",
              value: args.slot3,
              className: classNames(sty.slotTargetSlot3),
            })
          : null}
        {(
          hasVariant(variants, "isOwner", "isOwner") &&
          hasVariant(variants, "userVariant", "isRequested")
            ? true
            : hasVariant(variants, "isOwner", "isOwner") &&
              hasVariant(variants, "userVariant", "isMember")
            ? true
            : hasVariant(variants, "userVariant", "isSelf")
            ? true
            : hasVariant(variants, "userVariant", "isMember")
            ? true
            : hasVariant(variants, "userVariant", "isRequested")
            ? true
            : true
        ) ? (
          <IconAdminIcon
            className={classNames(projectcss.all, sty.svg__dd2Hx, {
              [sty.svguserVariant_isAdmin_isOwner__dd2Hx35UokPkRzz]:
                hasVariant(variants, "isOwner", "isOwner") &&
                hasVariant(variants, "userVariant", "isAdmin"),
              [sty.svguserVariant_isMember__dd2HxgdyZr]: hasVariant(
                variants,
                "userVariant",
                "isMember"
              ),
              [sty.svguserVariant_isMember_isOwner__dd2HxgdyZrPkRzz]:
                hasVariant(variants, "isOwner", "isOwner") &&
                hasVariant(variants, "userVariant", "isMember"),
              [sty.svguserVariant_isRequested__dd2HXoSddm]: hasVariant(
                variants,
                "userVariant",
                "isRequested"
              ),
              [sty.svguserVariant_isRequested_isOwner__dd2HXoSddmPkRzz]:
                hasVariant(variants, "isOwner", "isOwner") &&
                hasVariant(variants, "userVariant", "isRequested"),
              [sty.svguserVariant_isSelf__dd2HxaAx2Z]: hasVariant(
                variants,
                "userVariant",
                "isSelf"
              ),
              [sty.svguserVariant_isSelf_isOwner__dd2HxaAx2ZPkRzz]:
                hasVariant(variants, "isOwner", "isOwner") &&
                hasVariant(variants, "userVariant", "isSelf"),
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {(hasVariant(variants, "userVariant", "isMember") ? true : true) ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(projectcss.all, sty.freeBox__ymOfc, {
            [sty.freeBoxuserVariant_isMember__ymOfcGdyZr]: hasVariant(
              variants,
              "userVariant",
              "isMember"
            ),
            [sty.freeBoxuserVariant_isMember_isOwner__ymOfcGdyZrPkRzz]:
              hasVariant(variants, "isOwner", "isOwner") &&
              hasVariant(variants, "userVariant", "isMember"),
            [sty.freeBoxuserVariant_isRequested__ymOfcoSddm]: hasVariant(
              variants,
              "userVariant",
              "isRequested"
            ),
            [sty.freeBoxuserVariant_isSelf__ymOfcAAx2Z]: hasVariant(
              variants,
              "userVariant",
              "isSelf"
            ),
            [sty.freeBoxuserVariant_isSelf_isOwner__ymOfcAAx2ZPkRzz]:
              hasVariant(variants, "userVariant", "isSelf") &&
              hasVariant(variants, "isOwner", "isOwner"),
          })}
        >
          {(
            hasVariant(variants, "userVariant", "isSelf") &&
            hasVariant(variants, "isOwner", "isOwner")
              ? true
              : hasVariant(variants, "isOwner", "isOwner")
              ? true
              : hasVariant(variants, "userVariant", "isSelf")
              ? false
              : false
          ) ? (
            <IconButton
              data-plasmic-name={"iconButton"}
              data-plasmic-override={overrides.iconButton}
              className={classNames("__wab_instance", sty.iconButton, {
                [sty.iconButtonisDropdown]: hasVariant(
                  variants,
                  "isDropdown",
                  "isDropdown"
                ),
                [sty.iconButtonisDropdown_userVariant_isRequested_isOwner]:
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "userVariant", "isRequested"),
                [sty.iconButtonisOwner]: hasVariant(
                  variants,
                  "isOwner",
                  "isOwner"
                ),
                [sty.iconButtonuserVariant_isAdmin]: hasVariant(
                  variants,
                  "userVariant",
                  "isAdmin"
                ),
                [sty.iconButtonuserVariant_isAdmin_isDropdown]:
                  hasVariant(variants, "userVariant", "isAdmin") &&
                  hasVariant(variants, "isDropdown", "isDropdown"),
                [sty.iconButtonuserVariant_isAdmin_isDropdown_isOwner]:
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "userVariant", "isAdmin") &&
                  hasVariant(variants, "isOwner", "isOwner"),
                [sty.iconButtonuserVariant_isMember_isDropdown_isOwner]:
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "userVariant", "isMember"),
                [sty.iconButtonuserVariant_isRequested]: hasVariant(
                  variants,
                  "userVariant",
                  "isRequested"
                ),
                [sty.iconButtonuserVariant_isSelf]: hasVariant(
                  variants,
                  "userVariant",
                  "isSelf"
                ),
                [sty.iconButtonuserVariant_isSelf_isDropdown_isOwner]:
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "userVariant", "isSelf"),
                [sty.iconButtonuserVariant_isSelf_isOwner]:
                  hasVariant(variants, "userVariant", "isSelf") &&
                  hasVariant(variants, "isOwner", "isOwner"),
              })}
            >
              <IconDotMenuIcon
                className={classNames(projectcss.all, sty.svg__jmi9G, {
                  [sty.svgisOwner__jmi9GpkRzz]: hasVariant(
                    variants,
                    "isOwner",
                    "isOwner"
                  ),
                  [sty.svguserVariant_isAdmin__jmi9G35Uok]: hasVariant(
                    variants,
                    "userVariant",
                    "isAdmin"
                  ),
                  [sty.svguserVariant_isMember__jmi9GgdyZr]: hasVariant(
                    variants,
                    "userVariant",
                    "isMember"
                  ),
                  [sty.svguserVariant_isMember_isOwner__jmi9GgdyZrPkRzz]:
                    hasVariant(variants, "isOwner", "isOwner") &&
                    hasVariant(variants, "userVariant", "isMember"),
                  [sty.svguserVariant_isSelf__jmi9GaAx2Z]: hasVariant(
                    variants,
                    "userVariant",
                    "isSelf"
                  ),
                })}
                role={"img"}
              />
            </IconButton>
          ) : null}
          {(hasVariant(variants, "isDropdown", "isDropdown") ? true : true) ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"dropdown"}
              data-plasmic-override={overrides.dropdown}
              hasGap={true}
              className={classNames(projectcss.all, sty.dropdown, {
                [sty.dropdownisDropdown]: hasVariant(
                  variants,
                  "isDropdown",
                  "isDropdown"
                ),
                [sty.dropdownisDropdown_isOwner]:
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "isDropdown", "isDropdown"),
                [sty.dropdownisDropdown_userVariant_isRequested_isOwner]:
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "userVariant", "isRequested"),
                [sty.dropdownisOwner]: hasVariant(
                  variants,
                  "isOwner",
                  "isOwner"
                ),
                [sty.dropdownuserVariant_isAdmin_isDropdown_isOwner]:
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "userVariant", "isAdmin"),
                [sty.dropdownuserVariant_isMember_isDropdown]:
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "userVariant", "isMember"),
                [sty.dropdownuserVariant_isMember_isDropdown_isOwner]:
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "userVariant", "isMember"),
                [sty.dropdownuserVariant_isMember_isOwner]:
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "userVariant", "isMember"),
                [sty.dropdownuserVariant_isRequested]: hasVariant(
                  variants,
                  "userVariant",
                  "isRequested"
                ),
                [sty.dropdownuserVariant_isSelf_isDropdown_isOwner]:
                  hasVariant(variants, "isOwner", "isOwner") &&
                  hasVariant(variants, "isDropdown", "isDropdown") &&
                  hasVariant(variants, "userVariant", "isSelf"),
              })}
            >
              {(
                hasVariant(variants, "isOwner", "isOwner") &&
                hasVariant(variants, "isDropdown", "isDropdown") &&
                hasVariant(variants, "userVariant", "isMember")
                  ? true
                  : hasVariant(variants, "isOwner", "isOwner") &&
                    hasVariant(variants, "userVariant", "isAdmin") &&
                    hasVariant(variants, "isDropdown", "isDropdown")
                  ? true
                  : hasVariant(variants, "isOwner", "isOwner") &&
                    hasVariant(variants, "userVariant", "isMember")
                  ? true
                  : hasVariant(variants, "userVariant", "isSelf")
                  ? false
                  : true
              ) ? (
                <ListItem
                  data-plasmic-name={"removeInvitation"}
                  data-plasmic-override={overrides.removeInvitation}
                  className={classNames(
                    "__wab_instance",
                    sty.removeInvitation,
                    {
                      [sty.removeInvitationisDropdown]: hasVariant(
                        variants,
                        "isDropdown",
                        "isDropdown"
                      ),
                      [sty.removeInvitationisDropdown_userVariant_isRequested_isOwner]:
                        hasVariant(variants, "isOwner", "isOwner") &&
                        hasVariant(variants, "isDropdown", "isDropdown") &&
                        hasVariant(variants, "userVariant", "isRequested"),
                      [sty.removeInvitationuserVariant_isAdmin_isDropdown_isOwner]:
                        hasVariant(variants, "isOwner", "isOwner") &&
                        hasVariant(variants, "userVariant", "isAdmin") &&
                        hasVariant(variants, "isDropdown", "isDropdown"),
                      [sty.removeInvitationuserVariant_isMember_isDropdown_isOwner]:
                        hasVariant(variants, "isOwner", "isOwner") &&
                        hasVariant(variants, "isDropdown", "isDropdown") &&
                        hasVariant(variants, "userVariant", "isMember"),
                      [sty.removeInvitationuserVariant_isMember_isOwner]:
                        hasVariant(variants, "isOwner", "isOwner") &&
                        hasVariant(variants, "userVariant", "isMember"),
                      [sty.removeInvitationuserVariant_isRequested]: hasVariant(
                        variants,
                        "userVariant",
                        "isRequested"
                      ),
                      [sty.removeInvitationuserVariant_isSelf]: hasVariant(
                        variants,
                        "userVariant",
                        "isSelf"
                      ),
                    }
                  )}
                  rename={"Remove member"}
                />
              ) : null}
            </p.Stack>
          ) : null}
          {(
            hasVariant(variants, "userVariant", "isSelf") &&
            hasVariant(variants, "isOwner", "isOwner")
              ? false
              : hasVariant(variants, "userVariant", "isAdmin")
              ? false
              : false
          ) ? (
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text___5GQ6G,
                {
                  [sty.textuserVariant_isAdmin___5GQ6G35Uok]: hasVariant(
                    variants,
                    "userVariant",
                    "isAdmin"
                  ),
                  [sty.textuserVariant_isMember___5GQ6GGdyZr]: hasVariant(
                    variants,
                    "userVariant",
                    "isMember"
                  ),
                  [sty.textuserVariant_isSelf___5GQ6GAAx2Z]: hasVariant(
                    variants,
                    "userVariant",
                    "isSelf"
                  ),
                  [sty.textuserVariant_isSelf_isOwner___5GQ6GAAx2ZPkRzz]:
                    hasVariant(variants, "userVariant", "isSelf") &&
                    hasVariant(variants, "isOwner", "isOwner"),
                }
              )}
            >
              {hasVariant(variants, "userVariant", "isSelf") &&
              hasVariant(variants, "isOwner", "isOwner")
                ? "Creator"
                : hasVariant(variants, "userVariant", "isAdmin")
                ? "Creator"
                : "Enter some text"}
            </div>
          ) : null}
        </p.Stack>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "photoAvatar",
    "userInitials",
    "iconButton",
    "dropdown",
    "removeInvitation",
  ],
  photoAvatar: ["photoAvatar", "userInitials"],
  userInitials: ["userInitials"],
  iconButton: ["iconButton"],
  dropdown: ["dropdown", "removeInvitation"],
  removeInvitation: ["removeInvitation"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  photoAvatar: typeof PhotoAvatar;
  userInitials: "div";
  iconButton: typeof IconButton;
  dropdown: "div";
  removeInvitation: typeof ListItem;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMemberItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMemberItem__VariantsArgs;
    args?: PlasmicMemberItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMemberItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMemberItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMemberItem__ArgProps,
      internalVariantPropNames: PlasmicMemberItem__VariantProps,
    });

    return PlasmicMemberItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMemberItem";
  } else {
    func.displayName = `PlasmicMemberItem.${nodeName}`;
  }
  return func;
}

export const PlasmicMemberItem = Object.assign(
  // Top-level PlasmicMemberItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    photoAvatar: makeNodeComponent("photoAvatar"),
    userInitials: makeNodeComponent("userInitials"),
    iconButton: makeNodeComponent("iconButton"),
    dropdown: makeNodeComponent("dropdown"),
    removeInvitation: makeNodeComponent("removeInvitation"),

    // Metadata about props expected for PlasmicMemberItem
    internalVariantProps: PlasmicMemberItem__VariantProps,
    internalArgProps: PlasmicMemberItem__ArgProps,
  }
);

export default PlasmicMemberItem;
/* prettier-ignore-end */
