// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mTVXT6w3HHjZ4d74q3gB76
// Component: eUnRsS9UXR
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import IconButton from "../../IconButton"; // plasmic-import: UIpuE7M1YY/component
import ErrorMessage from "../../ErrorMessage"; // plasmic-import: X8H70YUTyF/component
import Tags from "../../Tags"; // plasmic-import: 0wz8hGqZgNQ/component
import Button from "../../Button"; // plasmic-import: JU1t0P9pFY/component

import { useScreenVariants as useScreenVariantsszbTUtTUfDw81Pi } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: szbTUtTUfDW81Pi/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_shared.module.css"; // plasmic-import: mTVXT6w3HHjZ4d74q3gB76/projectcss
import sty from "./PlasmicActionBar.module.css"; // plasmic-import: eUnRsS9UXR/css

import IconFeedIcon from "./icons/PlasmicIcon__IconFeed"; // plasmic-import: gkIqWTG_m/icon
import IconEmojisvgIcon from "./icons/PlasmicIcon__IconEmojisvg"; // plasmic-import: 7EdfFx1qO/icon
import IconListsvgIcon from "./icons/PlasmicIcon__IconListsvg"; // plasmic-import: kGOcXPlB7/icon
import IconImagesvgIcon from "./icons/PlasmicIcon__IconImagesvg"; // plasmic-import: mIjXTEoTT/icon
import IconCautionIcon from "./icons/PlasmicIcon__IconCaution"; // plasmic-import: 9xu35mhQf/icon
import IconOvalIcon from "./icons/PlasmicIcon__IconOval"; // plasmic-import: FUAnm6q86/icon
import IconCloseIcon from "./icons/PlasmicIcon__IconClose"; // plasmic-import: v016HsKmfL/icon
import IconPlusIcon from "./icons/PlasmicIcon__IconPlus"; // plasmic-import: B5QLKmr2tW/icon
import IconSend2Icon from "./icons/PlasmicIcon__IconSend2"; // plasmic-import: Iea8iz1ew/icon

export type PlasmicActionBar__VariantMembers = {
  error: "hasError" | "unnamedVariant";
  text: "hasText";
  isActive: "isActive";
  timelineSelected: "timelineSelected";
  mobileLayout: "mobileLayout";
};

export type PlasmicActionBar__VariantsArgs = {
  error?: MultiChoiceArg<"hasError" | "unnamedVariant">;
  text?: MultiChoiceArg<"hasText">;
  isActive?: SingleBooleanChoiceArg<"isActive">;
  timelineSelected?: SingleBooleanChoiceArg<"timelineSelected">;
  mobileLayout?: SingleBooleanChoiceArg<"mobileLayout">;
};

type VariantPropType = keyof PlasmicActionBar__VariantsArgs;
export const PlasmicActionBar__VariantProps = new Array<VariantPropType>(
  "error",
  "text",
  "isActive",
  "timelineSelected",
  "mobileLayout"
);

export type PlasmicActionBar__ArgsType = {
  slot?: React.ReactNode;
  text2?: React.ReactNode;
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicActionBar__ArgsType;
export const PlasmicActionBar__ArgProps = new Array<ArgPropType>(
  "slot",
  "text2",
  "children"
);

export type PlasmicActionBar__OverridesType = {
  root?: p.Flex<"div">;
  form?: p.Flex<"form">;
  editorContainer?: p.Flex<"div">;
  title?: p.Flex<"textarea">;
  description?: p.Flex<"textarea">;
  emoji?: p.Flex<typeof IconButton>;
  bulletList?: p.Flex<typeof IconButton>;
  uploadImage?: p.Flex<typeof IconButton>;
  errorMessage?: p.Flex<typeof ErrorMessage>;
  characterLimitIndicator?: p.Flex<typeof IconButton>;
  shareToContainer?: p.Flex<"div">;
  container?: p.Flex<"div">;
  selectedItemsContainer?: p.Flex<"div">;
  tags?: p.Flex<typeof Tags>;
  text2?: p.Flex<"div">;
  button?: p.Flex<"button">;
  post?: p.Flex<typeof Button>;
  text23?: p.Flex<"div">;
};

export interface DefaultActionBarProps {
  slot?: React.ReactNode;
  text2?: React.ReactNode;
  children?: React.ReactNode;
  error?: MultiChoiceArg<"hasError" | "unnamedVariant">;
  text?: MultiChoiceArg<"hasText">;
  isActive?: SingleBooleanChoiceArg<"isActive">;
  timelineSelected?: SingleBooleanChoiceArg<"timelineSelected">;
  mobileLayout?: SingleBooleanChoiceArg<"mobileLayout">;
  className?: string;
}

export const defaultActionBar__Args: Partial<PlasmicActionBar__ArgsType> = {};

function PlasmicActionBar__RenderFunc(props: {
  variants: PlasmicActionBar__VariantsArgs;
  args: PlasmicActionBar__ArgsType;
  overrides: PlasmicActionBar__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultActionBar__Args, props.args);
  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsszbTUtTUfDw81Pi(),
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rooterror_hasError]: hasVariant(variants, "error", "hasError"),
          [sty.rootisActive]: hasVariant(variants, "isActive", "isActive"),
          [sty.rootisActive_error_hasError]:
            hasVariant(variants, "isActive", "isActive") &&
            hasVariant(variants, "error", "hasError"),
          [sty.roottext_hasText]: hasVariant(variants, "text", "hasText"),
          [sty.roottext_hasText_error_hasError]:
            hasVariant(variants, "text", "hasText") &&
            hasVariant(variants, "error", "hasError"),
          [sty.roottimelineSelected]: hasVariant(
            variants,
            "timelineSelected",
            "timelineSelected"
          ),
        }
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__zG8Do, {
          [sty.freeBoxerror_hasError__zG8DoxYqMt]: hasVariant(
            variants,
            "error",
            "hasError"
          ),
          [sty.freeBoxisActive__zG8DovjQpn]: hasVariant(
            variants,
            "isActive",
            "isActive"
          ),
          [sty.freeBoxtimelineSelected__zG8Do75BwG]: hasVariant(
            variants,
            "timelineSelected",
            "timelineSelected"
          ),
          [sty.freeBoxtimelineSelected_isActive__zG8Do75BwGVjQpn]:
            hasVariant(variants, "timelineSelected", "timelineSelected") &&
            hasVariant(variants, "isActive", "isActive"),
        })}
      >
        <form
          data-plasmic-name={"form"}
          data-plasmic-override={overrides.form}
          className={classNames(projectcss.all, sty.form, {
            [sty.formisActive]: hasVariant(variants, "isActive", "isActive"),
            [sty.formtimelineSelected]: hasVariant(
              variants,
              "timelineSelected",
              "timelineSelected"
            ),
            [sty.formtimelineSelected_isActive]:
              hasVariant(variants, "timelineSelected", "timelineSelected") &&
              hasVariant(variants, "isActive", "isActive"),
          })}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__ptnBs, {
              [sty.freeBoxisActive__ptnBsvjQpn]: hasVariant(
                variants,
                "isActive",
                "isActive"
              ),
            })}
          >
            <div
              data-plasmic-name={"editorContainer"}
              data-plasmic-override={overrides.editorContainer}
              className={classNames(projectcss.all, sty.editorContainer, {
                [sty.editorContainererror_hasError]: hasVariant(
                  variants,
                  "error",
                  "hasError"
                ),
                [sty.editorContainerisActive]: hasVariant(
                  variants,
                  "isActive",
                  "isActive"
                ),
                [sty.editorContainertext_hasText_error_hasError]:
                  hasVariant(variants, "text", "hasText") &&
                  hasVariant(variants, "error", "hasError"),
                [sty.editorContainertimelineSelected]: hasVariant(
                  variants,
                  "timelineSelected",
                  "timelineSelected"
                ),
              })}
            >
              <textarea
                data-plasmic-name={"title"}
                data-plasmic-override={overrides.title}
                className={classNames(
                  projectcss.all,
                  projectcss.textarea,
                  sty.title,
                  {
                    [sty.titleisActive]: hasVariant(
                      variants,
                      "isActive",
                      "isActive"
                    ),
                    [sty.titleisActive_error_hasError]:
                      hasVariant(variants, "isActive", "isActive") &&
                      hasVariant(variants, "error", "hasError"),
                    [sty.titletimelineSelected]: hasVariant(
                      variants,
                      "timelineSelected",
                      "timelineSelected"
                    ),
                    [sty.titletimelineSelected_isActive]:
                      hasVariant(
                        variants,
                        "timelineSelected",
                        "timelineSelected"
                      ) && hasVariant(variants, "isActive", "isActive"),
                  }
                )}
                placeholder={"Write your update..." as const}
                rows={
                  hasVariant(variants, "isActive", "isActive") &&
                  hasVariant(globalVariants, "screen", "mobile")
                    ? (5 as const)
                    : hasVariant(variants, "isActive", "isActive")
                    ? (1 as const)
                    : undefined
                }
              />

              {(hasVariant(variants, "isActive", "isActive") ? true : false) ? (
                <textarea
                  data-plasmic-name={"description"}
                  data-plasmic-override={overrides.description}
                  className={classNames(
                    projectcss.all,
                    projectcss.textarea,
                    sty.description,
                    {
                      [sty.descriptionisActive]: hasVariant(
                        variants,
                        "isActive",
                        "isActive"
                      ),
                      [sty.descriptionisActive_error_hasError]:
                        hasVariant(variants, "isActive", "isActive") &&
                        hasVariant(variants, "error", "hasError"),
                      [sty.descriptiontimelineSelected]: hasVariant(
                        variants,
                        "timelineSelected",
                        "timelineSelected"
                      ),
                      [sty.descriptiontimelineSelected_isActive]:
                        hasVariant(
                          variants,
                          "timelineSelected",
                          "timelineSelected"
                        ) && hasVariant(variants, "isActive", "isActive"),
                    }
                  )}
                  placeholder={
                    hasVariant(variants, "isActive", "isActive")
                      ? ("Description..." as const)
                      : ("Write a paragraph" as const)
                  }
                  rows={2 as const}
                  value={"" as const}
                />
              ) : null}
            </div>

            {(hasVariant(variants, "isActive", "isActive") ? true : false) ? (
              <div
                className={classNames(projectcss.all, sty.freeBox__hHc69, {
                  [sty.freeBoxisActive__hHc69VjQpn]: hasVariant(
                    variants,
                    "isActive",
                    "isActive"
                  ),
                })}
              >
                {(
                  hasVariant(variants, "isActive", "isActive") ? true : false
                ) ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1SVGi, {
                      [sty.freeBoxisActive___1SVGivjQpn]: hasVariant(
                        variants,
                        "isActive",
                        "isActive"
                      ),
                    })}
                  >
                    {(
                      hasVariant(variants, "isActive", "isActive")
                        ? true
                        : false
                    ) ? (
                      <IconButton
                        data-plasmic-name={"emoji"}
                        data-plasmic-override={overrides.emoji}
                        className={classNames("__wab_instance", sty.emoji, {
                          [sty.emojiisActive]: hasVariant(
                            variants,
                            "isActive",
                            "isActive"
                          ),
                        })}
                        iconSize={
                          hasVariant(variants, "isActive", "isActive")
                            ? ("large" as const)
                            : undefined
                        }
                      >
                        <p.PlasmicIcon
                          PlasmicIconType={
                            hasVariant(variants, "isActive", "isActive")
                              ? IconEmojisvgIcon
                              : IconFeedIcon
                          }
                          className={classNames(projectcss.all, sty.svg__xoE5, {
                            [sty.svgisActive__xoE5VjQpn]: hasVariant(
                              variants,
                              "isActive",
                              "isActive"
                            ),
                          })}
                          role={"img"}
                        />
                      </IconButton>
                    ) : null}
                    {(
                      hasVariant(variants, "isActive", "isActive")
                        ? true
                        : false
                    ) ? (
                      <IconButton
                        data-plasmic-name={"bulletList"}
                        data-plasmic-override={overrides.bulletList}
                        className={classNames(
                          "__wab_instance",
                          sty.bulletList,
                          {
                            [sty.bulletListisActive]: hasVariant(
                              variants,
                              "isActive",
                              "isActive"
                            ),
                          }
                        )}
                        iconSize={
                          hasVariant(variants, "isActive", "isActive")
                            ? ("large" as const)
                            : undefined
                        }
                      >
                        <p.PlasmicIcon
                          PlasmicIconType={
                            hasVariant(variants, "isActive", "isActive")
                              ? IconListsvgIcon
                              : IconFeedIcon
                          }
                          className={classNames(
                            projectcss.all,
                            sty.svg__t421V,
                            {
                              [sty.svgisActive__t421VvjQpn]: hasVariant(
                                variants,
                                "isActive",
                                "isActive"
                              ),
                            }
                          )}
                          role={"img"}
                        />
                      </IconButton>
                    ) : null}
                    {(
                      hasVariant(variants, "isActive", "isActive")
                        ? true
                        : false
                    ) ? (
                      <IconButton
                        data-plasmic-name={"uploadImage"}
                        data-plasmic-override={overrides.uploadImage}
                        className={classNames(
                          "__wab_instance",
                          sty.uploadImage,
                          {
                            [sty.uploadImageisActive]: hasVariant(
                              variants,
                              "isActive",
                              "isActive"
                            ),
                          }
                        )}
                        iconSize={
                          hasVariant(variants, "isActive", "isActive")
                            ? ("large" as const)
                            : undefined
                        }
                      >
                        <p.PlasmicIcon
                          PlasmicIconType={
                            hasVariant(variants, "isActive", "isActive")
                              ? IconImagesvgIcon
                              : IconFeedIcon
                          }
                          className={classNames(
                            projectcss.all,
                            sty.svg__zxbGe,
                            {
                              [sty.svgisActive__zxbGevjQpn]: hasVariant(
                                variants,
                                "isActive",
                                "isActive"
                              ),
                            }
                          )}
                          role={"img"}
                        />
                      </IconButton>
                    ) : null}
                  </p.Stack>
                ) : null}
                {(
                  hasVariant(variants, "isActive", "isActive") ? true : false
                ) ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___9ZsQ, {
                      [sty.freeBoxisActive___9ZsQvjQpn]: hasVariant(
                        variants,
                        "isActive",
                        "isActive"
                      ),
                      [sty.freeBoxisActive_error_hasError___9ZsQvjQpnXYqMt]:
                        hasVariant(variants, "isActive", "isActive") &&
                        hasVariant(variants, "error", "hasError"),
                    })}
                  >
                    {(
                      hasVariant(variants, "isActive", "isActive") &&
                      hasVariant(variants, "error", "hasError")
                        ? true
                        : false
                    ) ? (
                      <ErrorMessage
                        data-plasmic-name={"errorMessage"}
                        data-plasmic-override={overrides.errorMessage}
                        className={classNames("__wab_instance", {
                          [sty.errorMessageisActive]: hasVariant(
                            variants,
                            "isActive",
                            "isActive"
                          ),
                          [sty.errorMessageisActive_error_hasError]:
                            hasVariant(variants, "isActive", "isActive") &&
                            hasVariant(variants, "error", "hasError"),
                        })}
                        message={"Error message"}
                      />
                    ) : null}
                    {(
                      hasVariant(variants, "isActive", "isActive")
                        ? true
                        : false
                    ) ? (
                      <IconButton
                        data-plasmic-name={"characterLimitIndicator"}
                        data-plasmic-override={
                          overrides.characterLimitIndicator
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.characterLimitIndicator,
                          {
                            [sty.characterLimitIndicatorisActive]: hasVariant(
                              variants,
                              "isActive",
                              "isActive"
                            ),
                          }
                        )}
                        iconSize={
                          hasVariant(variants, "isActive", "isActive")
                            ? ("large" as const)
                            : undefined
                        }
                      >
                        <p.PlasmicIcon
                          PlasmicIconType={
                            hasVariant(variants, "isActive", "isActive")
                              ? IconOvalIcon
                              : IconFeedIcon
                          }
                          className={classNames(
                            projectcss.all,
                            sty.svg__j4Ijp,
                            {
                              [sty.svgisActive__j4IjpvjQpn]: hasVariant(
                                variants,
                                "isActive",
                                "isActive"
                              ),
                            }
                          )}
                          role={"img"}
                        />
                      </IconButton>
                    ) : null}
                  </p.Stack>
                ) : null}
              </div>
            ) : null}
          </p.Stack>
        </form>

        {(hasVariant(variants, "isActive", "isActive") ? true : false) ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__mQqJf, {
              [sty.freeBoxisActive__mQqJfvjQpn]: hasVariant(
                variants,
                "isActive",
                "isActive"
              ),
              [sty.freeBoxmobileLayout__mQqJfr8WpI]: hasVariant(
                variants,
                "mobileLayout",
                "mobileLayout"
              ),
              [sty.freeBoxtimelineSelected__mQqJf75BwG]: hasVariant(
                variants,
                "timelineSelected",
                "timelineSelected"
              ),
              [sty.freeBoxtimelineSelected_isActive__mQqJf75BwGVjQpn]:
                hasVariant(variants, "timelineSelected", "timelineSelected") &&
                hasVariant(variants, "isActive", "isActive"),
            })}
          >
            {(hasVariant(variants, "isActive", "isActive") ? true : false) ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kjkQr, {
                  [sty.freeBoxisActive__kjkQrvjQpn]: hasVariant(
                    variants,
                    "isActive",
                    "isActive"
                  ),
                  [sty.freeBoxtimelineSelected__kjkQr75BwG]: hasVariant(
                    variants,
                    "timelineSelected",
                    "timelineSelected"
                  ),
                })}
              >
                <div
                  className={classNames(projectcss.all, sty.freeBox__dWUd, {
                    [sty.freeBoxisActive__dWUdvjQpn]: hasVariant(
                      variants,
                      "isActive",
                      "isActive"
                    ),
                    [sty.freeBoxtimelineSelected__dWUd75BwG]: hasVariant(
                      variants,
                      "timelineSelected",
                      "timelineSelected"
                    ),
                    [sty.freeBoxtimelineSelected_isActive__dWUd75BwGVjQpn]:
                      hasVariant(
                        variants,
                        "timelineSelected",
                        "timelineSelected"
                      ) && hasVariant(variants, "isActive", "isActive"),
                  })}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"shareToContainer"}
                    data-plasmic-override={overrides.shareToContainer}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      sty.shareToContainer,
                      {
                        [sty.shareToContainerisActive]: hasVariant(
                          variants,
                          "isActive",
                          "isActive"
                        ),
                        [sty.shareToContainerisActive_error_hasError]:
                          hasVariant(variants, "isActive", "isActive") &&
                          hasVariant(variants, "error", "hasError"),
                        [sty.shareToContainermobileLayout]: hasVariant(
                          variants,
                          "mobileLayout",
                          "mobileLayout"
                        ),
                        [sty.shareToContainertimelineSelected]: hasVariant(
                          variants,
                          "timelineSelected",
                          "timelineSelected"
                        ),
                        [sty.shareToContainertimelineSelected_isActive]:
                          hasVariant(
                            variants,
                            "timelineSelected",
                            "timelineSelected"
                          ) && hasVariant(variants, "isActive", "isActive"),
                      }
                    )}
                  >
                    {(
                      hasVariant(variants, "isActive", "isActive")
                        ? true
                        : false
                    ) ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__iriP,
                          {
                            [sty.freeBoxisActive__iriPvjQpn]: hasVariant(
                              variants,
                              "isActive",
                              "isActive"
                            ),
                            [sty.freeBoxisActive_error_hasError__iriPvjQpnXYqMt]:
                              hasVariant(variants, "isActive", "isActive") &&
                              hasVariant(variants, "error", "hasError"),
                            [sty.freeBoxtimelineSelected__iriP75BwG]:
                              hasVariant(
                                variants,
                                "timelineSelected",
                                "timelineSelected"
                              ),
                          }
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vnwRg,
                            {
                              [sty.freeBoxisActive__vnwRgvjQpn]: hasVariant(
                                variants,
                                "isActive",
                                "isActive"
                              ),
                              [sty.freeBoxisActive_error_hasError__vnwRgvjQpnXYqMt]:
                                hasVariant(variants, "isActive", "isActive") &&
                                hasVariant(variants, "error", "hasError"),
                              [sty.freeBoxtimelineSelected__vnwRg75BwG]:
                                hasVariant(
                                  variants,
                                  "timelineSelected",
                                  "timelineSelected"
                                ),
                            }
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__pYpv,
                              {
                                [sty.textisActive__pYpVvjQpn]: hasVariant(
                                  variants,
                                  "isActive",
                                  "isActive"
                                ),
                                [sty.textisActive_error_hasError__pYpVvjQpnXYqMt]:
                                  hasVariant(
                                    variants,
                                    "isActive",
                                    "isActive"
                                  ) &&
                                  hasVariant(variants, "error", "hasError"),
                                [sty.texttimelineSelected__pYpv75BwG]:
                                  hasVariant(
                                    variants,
                                    "timelineSelected",
                                    "timelineSelected"
                                  ),
                              }
                            )}
                          >
                            {hasVariant(variants, "isActive", "isActive")
                              ? "Post to:"
                              : "Share to:"}
                          </div>
                        </div>
                      </p.Stack>
                    ) : null}
                  </p.Stack>

                  {(
                    hasVariant(variants, "timelineSelected", "timelineSelected")
                      ? true
                      : false
                  ) ? (
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"container"}
                      data-plasmic-override={overrides.container}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.container, {
                        [sty.containerisActive]: hasVariant(
                          variants,
                          "isActive",
                          "isActive"
                        ),
                        [sty.containertimelineSelected]: hasVariant(
                          variants,
                          "timelineSelected",
                          "timelineSelected"
                        ),
                        [sty.containertimelineSelected_isActive]:
                          hasVariant(variants, "isActive", "isActive") &&
                          hasVariant(
                            variants,
                            "timelineSelected",
                            "timelineSelected"
                          ),
                      })}
                    >
                      {(
                        hasVariant(variants, "isActive", "isActive") &&
                        hasVariant(
                          variants,
                          "timelineSelected",
                          "timelineSelected"
                        )
                          ? true
                          : false
                      ) ? (
                        <div
                          data-plasmic-name={"selectedItemsContainer"}
                          data-plasmic-override={
                            overrides.selectedItemsContainer
                          }
                          className={classNames(
                            projectcss.all,
                            sty.selectedItemsContainer,
                            {
                              [sty.selectedItemsContainerisActive]: hasVariant(
                                variants,
                                "isActive",
                                "isActive"
                              ),
                              [sty.selectedItemsContainertimelineSelected]:
                                hasVariant(
                                  variants,
                                  "timelineSelected",
                                  "timelineSelected"
                                ),
                              [sty.selectedItemsContainertimelineSelected_isActive]:
                                hasVariant(variants, "isActive", "isActive") &&
                                hasVariant(
                                  variants,
                                  "timelineSelected",
                                  "timelineSelected"
                                ),
                            }
                          )}
                        >
                          {(
                            hasVariant(variants, "isActive", "isActive") &&
                            hasVariant(
                              variants,
                              "timelineSelected",
                              "timelineSelected"
                            )
                              ? false
                              : false
                          ) ? (
                            <Tags
                              data-plasmic-name={"tags"}
                              data-plasmic-override={overrides.tags}
                              className={classNames(
                                "__wab_instance",
                                sty.tags,
                                {
                                  [sty.tagstimelineSelected_isActive]:
                                    hasVariant(
                                      variants,
                                      "isActive",
                                      "isActive"
                                    ) &&
                                    hasVariant(
                                      variants,
                                      "timelineSelected",
                                      "timelineSelected"
                                    ),
                                }
                              )}
                              text2={
                                <div
                                  data-plasmic-name={"text2"}
                                  data-plasmic-override={overrides.text2}
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text2
                                  )}
                                >
                                  {"Tag Name"}
                                </div>
                              }
                            >
                              <IconCloseIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__hwNLe
                                )}
                                role={"img"}
                              />
                            </Tags>
                          ) : null}
                          {(
                            hasVariant(variants, "isActive", "isActive") &&
                            hasVariant(
                              variants,
                              "timelineSelected",
                              "timelineSelected"
                            )
                              ? true
                              : false
                          ) ? (
                            <button
                              data-plasmic-name={"button"}
                              data-plasmic-override={overrides.button}
                              className={classNames(
                                projectcss.all,
                                projectcss.button,
                                sty.button,
                                {
                                  [sty.buttonisActive]: hasVariant(
                                    variants,
                                    "isActive",
                                    "isActive"
                                  ),
                                  [sty.buttontimelineSelected_isActive]:
                                    hasVariant(
                                      variants,
                                      "isActive",
                                      "isActive"
                                    ) &&
                                    hasVariant(
                                      variants,
                                      "timelineSelected",
                                      "timelineSelected"
                                    ),
                                }
                              )}
                            >
                              <p.Stack
                                as={"div"}
                                hasGap={true}
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__kBcf
                                )}
                              >
                                {(
                                  hasVariant(
                                    variants,
                                    "isActive",
                                    "isActive"
                                  ) &&
                                  hasVariant(
                                    variants,
                                    "timelineSelected",
                                    "timelineSelected"
                                  )
                                    ? false
                                    : true
                                )
                                  ? p.renderPlasmicSlot({
                                      defaultContents: (
                                        <IconPlusIcon
                                          className={classNames(
                                            projectcss.all,
                                            sty.svg__niToo
                                          )}
                                          role={"img"}
                                        />
                                      ),

                                      value: args.slot,
                                    })
                                  : null}
                                {p.renderPlasmicSlot({
                                  defaultContents: (
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__qsrpV
                                      )}
                                    >
                                      {"Metric"}
                                    </div>
                                  ),

                                  value: args.text2,
                                  className: classNames(sty.slotTargetText2, {
                                    [sty.slotTargetText2isActive]: hasVariant(
                                      variants,
                                      "isActive",
                                      "isActive"
                                    ),
                                    [sty.slotTargetText2timelineSelected_isActive]:
                                      hasVariant(
                                        variants,
                                        "isActive",
                                        "isActive"
                                      ) &&
                                      hasVariant(
                                        variants,
                                        "timelineSelected",
                                        "timelineSelected"
                                      ),
                                  }),
                                })}

                                {p.renderPlasmicSlot({
                                  defaultContents: (
                                    <IconCloseIcon
                                      className={classNames(
                                        projectcss.all,
                                        sty.svg__kMNxX
                                      )}
                                      role={"img"}
                                    />
                                  ),

                                  value: args.children,
                                  className: classNames(sty.slotTargetChildren),
                                })}
                              </p.Stack>
                            </button>
                          ) : null}
                        </div>
                      ) : null}
                    </p.Stack>
                  ) : null}
                </div>

                {(
                  hasVariant(variants, "isActive", "isActive") ? true : false
                ) ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__d8M3B, {
                      [sty.freeBoxisActive__d8M3BvjQpn]: hasVariant(
                        variants,
                        "isActive",
                        "isActive"
                      ),
                    })}
                  >
                    <Button
                      data-plasmic-name={"post"}
                      data-plasmic-override={overrides.post}
                      buttonFeatures={
                        hasVariant(variants, "mobileLayout", "mobileLayout")
                          ? []
                          : hasVariant(variants, "isActive", "isActive") &&
                            hasVariant(globalVariants, "screen", "mobile")
                          ? ["nonFullWidth"]
                          : []
                      }
                      buttonStyle={
                        hasVariant(variants, "isActive", "isActive")
                          ? undefined
                          : ("primaryPurple" as const)
                      }
                      className={classNames("__wab_instance", sty.post, {
                        [sty.postisActive]: hasVariant(
                          variants,
                          "isActive",
                          "isActive"
                        ),
                        [sty.postisActive_error_hasError]:
                          hasVariant(variants, "isActive", "isActive") &&
                          hasVariant(variants, "error", "hasError"),
                        [sty.postmobileLayout]: hasVariant(
                          variants,
                          "mobileLayout",
                          "mobileLayout"
                        ),
                        [sty.posttimelineSelected_isActive]:
                          hasVariant(variants, "isActive", "isActive") &&
                          hasVariant(
                            variants,
                            "timelineSelected",
                            "timelineSelected"
                          ),
                      })}
                      count={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__az4AZ
                          )}
                        >
                          {"1"}
                        </div>
                      }
                      isDisabled={
                        hasVariant(variants, "isActive", "isActive") &&
                        hasVariant(
                          variants,
                          "timelineSelected",
                          "timelineSelected"
                        )
                          ? undefined
                          : hasVariant(variants, "isActive", "isActive") &&
                            hasVariant(variants, "error", "hasError")
                          ? undefined
                          : hasVariant(variants, "isActive", "isActive")
                          ? true
                          : true
                      }
                      slot={
                        <IconPlusIcon
                          className={classNames(projectcss.all, sty.svg__orOwz)}
                          role={"img"}
                        />
                      }
                      text2={
                        <div
                          data-plasmic-name={"text23"}
                          data-plasmic-override={overrides.text23}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text23,
                            {
                              [sty.text23isActive]: hasVariant(
                                variants,
                                "isActive",
                                "isActive"
                              ),
                            }
                          )}
                        >
                          {"Post"}
                        </div>
                      }
                    >
                      <IconSend2Icon
                        className={classNames(projectcss.all, sty.svg__ljFz)}
                        role={"img"}
                      />
                    </Button>
                  </div>
                ) : null}
              </p.Stack>
            ) : null}
          </p.Stack>
        ) : null}
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "form",
    "editorContainer",
    "title",
    "description",
    "emoji",
    "bulletList",
    "uploadImage",
    "errorMessage",
    "characterLimitIndicator",
    "shareToContainer",
    "container",
    "selectedItemsContainer",
    "tags",
    "text2",
    "button",
    "post",
    "text23",
  ],
  form: [
    "form",
    "editorContainer",
    "title",
    "description",
    "emoji",
    "bulletList",
    "uploadImage",
    "errorMessage",
    "characterLimitIndicator",
  ],
  editorContainer: ["editorContainer", "title", "description"],
  title: ["title"],
  description: ["description"],
  emoji: ["emoji"],
  bulletList: ["bulletList"],
  uploadImage: ["uploadImage"],
  errorMessage: ["errorMessage"],
  characterLimitIndicator: ["characterLimitIndicator"],
  shareToContainer: ["shareToContainer"],
  container: ["container", "selectedItemsContainer", "tags", "text2", "button"],
  selectedItemsContainer: ["selectedItemsContainer", "tags", "text2", "button"],
  tags: ["tags", "text2"],
  text2: ["text2"],
  button: ["button"],
  post: ["post", "text23"],
  text23: ["text23"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  form: "form";
  editorContainer: "div";
  title: "textarea";
  description: "textarea";
  emoji: typeof IconButton;
  bulletList: typeof IconButton;
  uploadImage: typeof IconButton;
  errorMessage: typeof ErrorMessage;
  characterLimitIndicator: typeof IconButton;
  shareToContainer: "div";
  container: "div";
  selectedItemsContainer: "div";
  tags: typeof Tags;
  text2: "div";
  button: "button";
  post: typeof Button;
  text23: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicActionBar__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicActionBar__VariantsArgs;
    args?: PlasmicActionBar__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicActionBar__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicActionBar__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicActionBar__ArgProps,
      internalVariantPropNames: PlasmicActionBar__VariantProps,
    });

    return PlasmicActionBar__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicActionBar";
  } else {
    func.displayName = `PlasmicActionBar.${nodeName}`;
  }
  return func;
}

export const PlasmicActionBar = Object.assign(
  // Top-level PlasmicActionBar renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    form: makeNodeComponent("form"),
    editorContainer: makeNodeComponent("editorContainer"),
    title: makeNodeComponent("title"),
    description: makeNodeComponent("description"),
    emoji: makeNodeComponent("emoji"),
    bulletList: makeNodeComponent("bulletList"),
    uploadImage: makeNodeComponent("uploadImage"),
    errorMessage: makeNodeComponent("errorMessage"),
    characterLimitIndicator: makeNodeComponent("characterLimitIndicator"),
    shareToContainer: makeNodeComponent("shareToContainer"),
    container: makeNodeComponent("container"),
    selectedItemsContainer: makeNodeComponent("selectedItemsContainer"),
    tags: makeNodeComponent("tags"),
    text2: makeNodeComponent("text2"),
    button: makeNodeComponent("button"),
    post: makeNodeComponent("post"),
    text23: makeNodeComponent("text23"),

    // Metadata about props expected for PlasmicActionBar
    internalVariantProps: PlasmicActionBar__VariantProps,
    internalArgProps: PlasmicActionBar__ArgProps,
  }
);

export default PlasmicActionBar;
/* prettier-ignore-end */
