// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mTVXT6w3HHjZ4d74q3gB76
// Component: LRwT0lHdps
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";
import IconButton from "../../IconButton"; // plasmic-import: UIpuE7M1YY/component
import IconButtonMember from "../../IconButtonMember"; // plasmic-import: ZhI9zuyxBT/component

import { useScreenVariants as useScreenVariantsszbTUtTUfDw81Pi } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: szbTUtTUfDW81Pi/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_shared.module.css"; // plasmic-import: mTVXT6w3HHjZ4d74q3gB76/projectcss
import sty from "./PlasmicMainHeader.module.css"; // plasmic-import: LRwT0lHdps/css

import IconExternalLinkIcon from "./icons/PlasmicIcon__IconExternalLink"; // plasmic-import: BDHiWdSyk/icon
import IconFeedIcon from "./icons/PlasmicIcon__IconFeed"; // plasmic-import: gkIqWTG_m/icon
import InfosvgIcon from "./icons/PlasmicIcon__Infosvg"; // plasmic-import: goVw5oohlB/icon

export type PlasmicMainHeader__VariantMembers = {
  headerStyles: "timelineHeader" | "ventureHeader" | "createNewVenture";
  isActive: "feed" | "members" | "settings" | "unnamedVariant";
  showVentureDescription: "showVentureDescription";
  isOnboarding: "isOnboarding";
  isPublic: "isPublic";
};

export type PlasmicMainHeader__VariantsArgs = {
  headerStyles?: SingleChoiceArg<
    "timelineHeader" | "ventureHeader" | "createNewVenture"
  >;
  isActive?: SingleChoiceArg<
    "feed" | "members" | "settings" | "unnamedVariant"
  >;
  showVentureDescription?: SingleBooleanChoiceArg<"showVentureDescription">;
  isOnboarding?: SingleBooleanChoiceArg<"isOnboarding">;
  isPublic?: SingleBooleanChoiceArg<"isPublic">;
};

type VariantPropType = keyof PlasmicMainHeader__VariantsArgs;
export const PlasmicMainHeader__VariantProps = new Array<VariantPropType>(
  "headerStyles",
  "isActive",
  "showVentureDescription",
  "isOnboarding",
  "isPublic"
);

export type PlasmicMainHeader__ArgsType = {
  timelineDescription?: React.ReactNode;
  timelineName?: React.ReactNode;
  ventureName?: React.ReactNode;
  ventureDescription?: React.ReactNode;
};

type ArgPropType = keyof PlasmicMainHeader__ArgsType;
export const PlasmicMainHeader__ArgProps = new Array<ArgPropType>(
  "timelineDescription",
  "timelineName",
  "ventureName",
  "ventureDescription"
);

export type PlasmicMainHeader__OverridesType = {
  container?: p.Flex<"div">;
  iconContainer?: p.Flex<"div">;
  viewHome?: p.Flex<typeof IconButton>;
  viewMembers?: p.Flex<typeof IconButtonMember>;
  viewSettings?: p.Flex<typeof IconButton>;
};

export interface DefaultMainHeaderProps {
  timelineDescription?: React.ReactNode;
  timelineName?: React.ReactNode;
  ventureName?: React.ReactNode;
  ventureDescription?: React.ReactNode;
  headerStyles?: SingleChoiceArg<
    "timelineHeader" | "ventureHeader" | "createNewVenture"
  >;
  isActive?: SingleChoiceArg<
    "feed" | "members" | "settings" | "unnamedVariant"
  >;
  showVentureDescription?: SingleBooleanChoiceArg<"showVentureDescription">;
  isOnboarding?: SingleBooleanChoiceArg<"isOnboarding">;
  isPublic?: SingleBooleanChoiceArg<"isPublic">;
  className?: string;
}

export const defaultMainHeader__Args: Partial<PlasmicMainHeader__ArgsType> = {};

function PlasmicMainHeader__RenderFunc(props: {
  variants: PlasmicMainHeader__VariantsArgs;
  args: PlasmicMainHeader__ArgsType;
  overrides: PlasmicMainHeader__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultMainHeader__Args, props.args);
  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsszbTUtTUfDw81Pi(),
  });

  return (
    true ? (
      <div
        data-plasmic-name={"container"}
        data-plasmic-override={overrides.container}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          sty.container,
          {
            [sty.containerheaderStyles_createNewVenture]: hasVariant(
              variants,
              "headerStyles",
              "createNewVenture"
            ),
            [sty.containerheaderStyles_timelineHeader]: hasVariant(
              variants,
              "headerStyles",
              "timelineHeader"
            ),
            [sty.containerheaderStyles_ventureHeader]: hasVariant(
              variants,
              "headerStyles",
              "ventureHeader"
            ),
            [sty.containerisActive_feed]: hasVariant(
              variants,
              "isActive",
              "feed"
            ),
          }
        )}
      >
        {(
          hasVariant(variants, "headerStyles", "createNewVenture")
            ? false
            : true
        ) ? (
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox___3Xg51, {
              [sty.freeBoxheaderStyles_createNewVenture___3Xg51K3Tru]:
                hasVariant(variants, "headerStyles", "createNewVenture"),
              [sty.freeBoxheaderStyles_timelineHeader___3Xg51Rxxpi]: hasVariant(
                variants,
                "headerStyles",
                "timelineHeader"
              ),
              [sty.freeBoxheaderStyles_ventureHeader___3Xg51NMQ9]: hasVariant(
                variants,
                "headerStyles",
                "ventureHeader"
              ),
            })}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__sDNfz, {
                [sty.freeBoxheaderStyles_createNewVenture__sDNfzk3Tru]:
                  hasVariant(variants, "headerStyles", "createNewVenture"),
                [sty.freeBoxheaderStyles_ventureHeader__sDNfzNMQ9]: hasVariant(
                  variants,
                  "headerStyles",
                  "ventureHeader"
                ),
              })}
            >
              {(
                hasVariant(variants, "headerStyles", "ventureHeader")
                  ? false
                  : true
              ) ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__yHtqj, {
                    [sty.freeBoxheaderStyles_createNewVenture__yHtqJk3Tru]:
                      hasVariant(variants, "headerStyles", "createNewVenture"),
                    [sty.freeBoxheaderStyles_timelineHeader__yHtqjRxxpi]:
                      hasVariant(variants, "headerStyles", "timelineHeader"),
                    [sty.freeBoxheaderStyles_ventureHeader__yHtqjnMQ9]:
                      hasVariant(variants, "headerStyles", "ventureHeader"),
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents: "Wins",
                    value: args.timelineName,
                    className: classNames(sty.slotTargetTimelineName, {
                      [sty.slotTargetTimelineNameheaderStyles_timelineHeader]:
                        hasVariant(variants, "headerStyles", "timelineHeader"),
                      [sty.slotTargetTimelineNameheaderStyles_ventureHeader]:
                        hasVariant(variants, "headerStyles", "ventureHeader"),
                    }),
                  })}
                </p.Stack>
              ) : null}
              {(
                hasVariant(variants, "headerStyles", "ventureHeader")
                  ? true
                  : hasVariant(variants, "headerStyles", "timelineHeader")
                  ? true
                  : false
              ) ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6YZlv, {
                    [sty.freeBoxheaderStyles_timelineHeader___6YZlvRxxpi]:
                      hasVariant(variants, "headerStyles", "timelineHeader"),
                    [sty.freeBoxheaderStyles_ventureHeader___6YZlvnMQ9]:
                      hasVariant(variants, "headerStyles", "ventureHeader"),
                  })}
                >
                  {(
                    hasVariant(variants, "headerStyles", "timelineHeader")
                      ? true
                      : false
                  ) ? (
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__y7S0J,
                        {
                          [sty.textheaderStyles_timelineHeader__y7S0JRxxpi]:
                            hasVariant(
                              variants,
                              "headerStyles",
                              "timelineHeader"
                            ),
                          [sty.textheaderStyles_ventureHeader__y7S0JNMQ9]:
                            hasVariant(
                              variants,
                              "headerStyles",
                              "ventureHeader"
                            ),
                        }
                      )}
                    >
                      {hasVariant(variants, "headerStyles", "timelineHeader")
                        ? "@"
                        : "Enter some text"}
                    </div>
                  ) : null}
                  {(
                    hasVariant(variants, "headerStyles", "timelineHeader")
                      ? true
                      : true
                  )
                    ? p.renderPlasmicSlot({
                        defaultContents: (
                          <React.Fragment>
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__oBTp
                              )}
                            >
                              {"Adbloom"}
                            </div>

                            {false ? (
                              <IconButton
                                className={classNames(
                                  "__wab_instance",
                                  sty.iconButton__buruf
                                )}
                                iconSize={"large" as const}
                              >
                                <IconExternalLinkIcon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__vIuG
                                  )}
                                  role={"img"}
                                />
                              </IconButton>
                            ) : null}
                          </React.Fragment>
                        ),
                        value: args.ventureName,
                        className: classNames(sty.slotTargetVentureName, {
                          [sty.slotTargetVentureNameheaderStyles_timelineHeader]:
                            hasVariant(
                              variants,
                              "headerStyles",
                              "timelineHeader"
                            ),
                        }),
                      })
                    : null}
                </p.Stack>
              ) : null}
              {(
                hasVariant(
                  variants,
                  "showVentureDescription",
                  "showVentureDescription"
                ) && hasVariant(variants, "headerStyles", "ventureHeader")
                  ? false
                  : hasVariant(
                      variants,
                      "showVentureDescription",
                      "showVentureDescription"
                    )
                  ? true
                  : hasVariant(variants, "headerStyles", "ventureHeader")
                  ? false
                  : hasVariant(variants, "headerStyles", "timelineHeader")
                  ? false
                  : hasVariant(globalVariants, "screen", "mobile")
                  ? false
                  : false
              ) ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox__fohK2, {
                    [sty.freeBoxheaderStyles_timelineHeader__fohK2Rxxpi]:
                      hasVariant(variants, "headerStyles", "timelineHeader"),
                    [sty.freeBoxheaderStyles_ventureHeader__fohK2NMQ9]:
                      hasVariant(variants, "headerStyles", "ventureHeader"),
                    [sty.freeBoxheaderStyles_ventureHeader_showVentureDescription__fohK2NMQ9CtI95]:
                      hasVariant(
                        variants,
                        "showVentureDescription",
                        "showVentureDescription"
                      ) &&
                      hasVariant(variants, "headerStyles", "ventureHeader"),
                    [sty.freeBoxshowVentureDescription__fohK2CtI95]: hasVariant(
                      variants,
                      "showVentureDescription",
                      "showVentureDescription"
                    ),
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents:
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    value: args.timelineDescription,
                    className: classNames(sty.slotTargetTimelineDescription, {
                      [sty.slotTargetTimelineDescriptionheaderStyles_timelineHeader]:
                        hasVariant(variants, "headerStyles", "timelineHeader"),
                      [sty.slotTargetTimelineDescriptionheaderStyles_timelineHeader_showVentureDescription]:
                        hasVariant(
                          variants,
                          "headerStyles",
                          "timelineHeader"
                        ) &&
                        hasVariant(
                          variants,
                          "showVentureDescription",
                          "showVentureDescription"
                        ),
                      [sty.slotTargetTimelineDescriptionheaderStyles_ventureHeader]:
                        hasVariant(variants, "headerStyles", "ventureHeader"),
                      [sty.slotTargetTimelineDescriptionheaderStyles_ventureHeader_showVentureDescription]:
                        hasVariant(
                          variants,
                          "showVentureDescription",
                          "showVentureDescription"
                        ) &&
                        hasVariant(variants, "headerStyles", "ventureHeader"),
                      [sty.slotTargetTimelineDescriptionshowVentureDescription]:
                        hasVariant(
                          variants,
                          "showVentureDescription",
                          "showVentureDescription"
                        ),
                    }),
                  })}
                </div>
              ) : null}
              {(
                hasVariant(variants, "headerStyles", "timelineHeader") &&
                hasVariant(
                  variants,
                  "showVentureDescription",
                  "showVentureDescription"
                )
                  ? false
                  : hasVariant(
                      variants,
                      "showVentureDescription",
                      "showVentureDescription"
                    )
                  ? true
                  : hasVariant(variants, "headerStyles", "createNewVenture")
                  ? false
                  : hasVariant(variants, "headerStyles", "ventureHeader")
                  ? false
                  : hasVariant(variants, "headerStyles", "timelineHeader")
                  ? false
                  : hasVariant(globalVariants, "screen", "mobile")
                  ? false
                  : true
              ) ? (
                <div
                  className={classNames(projectcss.all, sty.freeBox__gg4AP, {
                    [sty.freeBoxheaderStyles_createNewVenture__gg4APk3Tru]:
                      hasVariant(variants, "headerStyles", "createNewVenture"),
                    [sty.freeBoxheaderStyles_timelineHeader__gg4APRxxpi]:
                      hasVariant(variants, "headerStyles", "timelineHeader"),
                    [sty.freeBoxheaderStyles_timelineHeader_showVentureDescription__gg4APRxxpiCtI95]:
                      hasVariant(variants, "headerStyles", "timelineHeader") &&
                      hasVariant(
                        variants,
                        "showVentureDescription",
                        "showVentureDescription"
                      ),
                    [sty.freeBoxheaderStyles_ventureHeader__gg4APnMQ9]:
                      hasVariant(variants, "headerStyles", "ventureHeader"),
                    [sty.freeBoxshowVentureDescription__gg4APctI95]: hasVariant(
                      variants,
                      "showVentureDescription",
                      "showVentureDescription"
                    ),
                  })}
                >
                  {p.renderPlasmicSlot({
                    defaultContents:
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec volutpat magna.",
                    value: args.ventureDescription,
                    className: classNames(sty.slotTargetVentureDescription, {
                      [sty.slotTargetVentureDescriptionheaderStyles_timelineHeader]:
                        hasVariant(variants, "headerStyles", "timelineHeader"),
                      [sty.slotTargetVentureDescriptionheaderStyles_ventureHeader]:
                        hasVariant(variants, "headerStyles", "ventureHeader"),
                      [sty.slotTargetVentureDescriptionshowVentureDescription]:
                        hasVariant(
                          variants,
                          "showVentureDescription",
                          "showVentureDescription"
                        ),
                    }),
                  })}
                </div>
              ) : null}
            </p.Stack>

            {(
              hasVariant(variants, "isOnboarding", "isOnboarding")
                ? false
                : hasVariant(variants, "headerStyles", "createNewVenture")
                ? false
                : true
            ) ? (
              <p.Stack
                as={"div"}
                data-plasmic-name={"iconContainer"}
                data-plasmic-override={overrides.iconContainer}
                hasGap={true}
                className={classNames(projectcss.all, sty.iconContainer, {
                  [sty.iconContainerheaderStyles_createNewVenture]: hasVariant(
                    variants,
                    "headerStyles",
                    "createNewVenture"
                  ),
                  [sty.iconContainerisActive_feed]: hasVariant(
                    variants,
                    "isActive",
                    "feed"
                  ),
                  [sty.iconContainerisOnboarding]: hasVariant(
                    variants,
                    "isOnboarding",
                    "isOnboarding"
                  ),
                })}
              >
                <IconButton
                  data-plasmic-name={"viewHome"}
                  data-plasmic-override={overrides.viewHome}
                  iconSize={"large" as const}
                  isActive={
                    hasVariant(variants, "isActive", "feed") ? true : undefined
                  }
                >
                  <IconFeedIcon
                    className={classNames(projectcss.all, sty.svg__eTdlE, {
                      [sty.svgheaderStyles_ventureHeader__eTdlEnMQ9]:
                        hasVariant(variants, "headerStyles", "ventureHeader"),
                      [sty.svgisActive_feed__eTdlEfnkZp]: hasVariant(
                        variants,
                        "isActive",
                        "feed"
                      ),
                    })}
                    role={"img"}
                  />
                </IconButton>

                {(
                  hasVariant(variants, "isPublic", "isPublic") ? false : true
                ) ? (
                  <IconButtonMember
                    data-plasmic-name={"viewMembers"}
                    data-plasmic-override={overrides.viewMembers}
                    className={classNames("__wab_instance", sty.viewMembers, {
                      [sty.viewMembersheaderStyles_ventureHeader]: hasVariant(
                        variants,
                        "headerStyles",
                        "ventureHeader"
                      ),
                      [sty.viewMembersisActive_feed]: hasVariant(
                        variants,
                        "isActive",
                        "feed"
                      ),
                      [sty.viewMembersisActive_members]: hasVariant(
                        variants,
                        "isActive",
                        "members"
                      ),
                      [sty.viewMembersisPublic]: hasVariant(
                        variants,
                        "isPublic",
                        "isPublic"
                      ),
                    })}
                    isActive={
                      hasVariant(variants, "isActive", "members")
                        ? true
                        : undefined
                    }
                    memberCount={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lssdr
                        )}
                      >
                        {"+"}
                      </div>
                    }
                  />
                ) : null}

                <IconButton
                  data-plasmic-name={"viewSettings"}
                  data-plasmic-override={overrides.viewSettings}
                  className={classNames("__wab_instance", sty.viewSettings, {
                    [sty.viewSettingsheaderStyles_ventureHeader]: hasVariant(
                      variants,
                      "headerStyles",
                      "ventureHeader"
                    ),
                    [sty.viewSettingsisActive_settings]: hasVariant(
                      variants,
                      "isActive",
                      "settings"
                    ),
                  })}
                  iconSize={"large" as const}
                  isActive={
                    hasVariant(variants, "isActive", "settings")
                      ? true
                      : undefined
                  }
                >
                  <InfosvgIcon
                    className={classNames(projectcss.all, sty.svg__isMis)}
                    role={"img"}
                  />
                </IconButton>
              </p.Stack>
            ) : null}
          </p.Stack>
        ) : null}
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  container: [
    "container",
    "iconContainer",
    "viewHome",
    "viewMembers",
    "viewSettings",
  ],
  iconContainer: ["iconContainer", "viewHome", "viewMembers", "viewSettings"],
  viewHome: ["viewHome"],
  viewMembers: ["viewMembers"],
  viewSettings: ["viewSettings"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  container: "div";
  iconContainer: "div";
  viewHome: typeof IconButton;
  viewMembers: typeof IconButtonMember;
  viewSettings: typeof IconButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMainHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMainHeader__VariantsArgs;
    args?: PlasmicMainHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMainHeader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMainHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMainHeader__ArgProps,
      internalVariantPropNames: PlasmicMainHeader__VariantProps,
    });

    return PlasmicMainHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "container") {
    func.displayName = "PlasmicMainHeader";
  } else {
    func.displayName = `PlasmicMainHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicMainHeader = Object.assign(
  // Top-level PlasmicMainHeader renders the root element
  makeNodeComponent("container"),
  {
    // Helper components rendering sub-elements
    iconContainer: makeNodeComponent("iconContainer"),
    viewHome: makeNodeComponent("viewHome"),
    viewMembers: makeNodeComponent("viewMembers"),
    viewSettings: makeNodeComponent("viewSettings"),

    // Metadata about props expected for PlasmicMainHeader
    internalVariantProps: PlasmicMainHeader__VariantProps,
    internalArgProps: PlasmicMainHeader__ArgProps,
  }
);

export default PlasmicMainHeader;
/* prettier-ignore-end */
