/** This file is auto-generated by Plasmic; please do not edit! */
import { useRouter } from "next/router";
import PlasmicLoader from "@plasmicapp/loader";

const componentsByPath = {
  
    "signin": {name: "Signin", projectId: "mTVXT6w3HHjZ4d74q3gB76" },
  
    "profile": {name: "Profile", projectId: "mTVXT6w3HHjZ4d74q3gB76" },
  
    "home": {name: "Home", projectId: "mTVXT6w3HHjZ4d74q3gB76" },
  
    "-2": {name: "Members", projectId: "mTVXT6w3HHjZ4d74q3gB76" },
  
    "-2-2": {name: "VentureSettings", projectId: "mTVXT6w3HHjZ4d74q3gB76" },
  
    "profile-2": {name: "JoinVenture", projectId: "mTVXT6w3HHjZ4d74q3gB76" },
  
    "landing": {name: "Homepage", projectId: "htDwGmRhKKr2sReJspzzGk" },
  
};

export default function PlasmicLoaderPage() {
  const router = useRouter();
  let { plasmicLoaderPage } = router.query;
  if (Array.isArray(plasmicLoaderPage)) {
    plasmicLoaderPage = plasmicLoaderPage.join('/');
  }
  const {name, projectId} = componentsByPath[plasmicLoaderPage];

  return <PlasmicLoader component={name} projectId={projectId} />;
}

export async function getStaticProps() {
  return {
    props: {},
  };
}

export async function getStaticPaths() {
  return {
    paths: [
      
        { params: { plasmicLoaderPage: ["signin",] } },
      
        { params: { plasmicLoaderPage: ["profile",] } },
      
        { params: { plasmicLoaderPage: ["home",] } },
      
        { params: { plasmicLoaderPage: ["-2",] } },
      
        { params: { plasmicLoaderPage: ["-2-2",] } },
      
        { params: { plasmicLoaderPage: ["profile-2",] } },
      
        { params: { plasmicLoaderPage: ["landing",] } },
      
    ],
    fallback: false,
  };
}
