/** This file is auto-generated by Plasmic; please do not edit! */

import * as React from "react";
import PlasmicLoader from "@plasmicapp/loader";
import dynamic from "next/dynamic";
import Link from "next/link";

export default function Home() {
  const Referlist = dynamic(
    () =>
      import("referlist").then((referlist) =>
        referlist.initialize({ domain: "venturemark" })
      ),
    { ssr: false }
  );

  return (
    <>
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-100italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-200.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-200italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-300.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-regular.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-500italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-500.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-600.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-700.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-600italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-700italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-800.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-800italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-900.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-900italic.ttf"
        as="font"
        crossOrigin=""
      />
      <link
        rel="preload"
        href="/fonts/poppins/poppins-v15-latin-100.ttf"
        as="font"
        crossOrigin=""
      />
      <Referlist />
      <PlasmicLoader
        projectId="htDwGmRhKKr2sReJspzzGk"
        component="Homepage"
        componentProps={{
          title: "Landing",
          privacyPolicy: {
            wrap: (node) => (
              <Link href="/privacy">
                <a>{node}</a>
              </Link>
            ),
          },
          join1: {
            type: "button",
            id: "referlistbutton",
          },
          email1: {
            id: "referlistemail",
            name: "emailAddress",
          },
          join2: {
            type: "button",
            id: "referlistbutton",
          },
          email2: {
            id: "referlistemail",
            color: "dark",
            name: "emailAddress2",
          },
        }}
      />
    </>
  );
}
