/** This file is auto-generated by Plasmic; please do not edit! */

import * as React from "react";
import PlasmicLoader from "@plasmicapp/loader";
import dynamic from "next/dynamic";
import Link from "next/link";

export default function Home() {
  const Referlist = dynamic(
    () =>
      import("referlist").then((referlist) =>
        referlist.initialize({ domain: "venturemark" })
      ),
    { ssr: false }
  );

  return (
    <>
      <Referlist />
      <PlasmicLoader
        projectId="htDwGmRhKKr2sReJspzzGk"
        component="Homepage"
        componentProps={{
          title: "Landing",
          privacyPolicy: {
            wrap: (node) => (
              <Link href="/privacy">
                <a>{node}</a>
              </Link>
            ),
          },
          join1: {
            type: "button",
            id: "referlistbutton",
          },
          email1: {
            id: "referlistemail",
            name: "emailAddress",
          },
          join2: {
            type: "button",
            id: "referlistbutton",
          },
          email2: {
            id: "referlistemail",
            color: "dark",
            name: "emailAddress2",
          },
        }}
      />
    </>
  );
}
