// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicLandingInput } from "./plasmic/venturemark/PlasmicLandingInput";

function LandingInput(props) {
  return (
    <PlasmicLandingInput
      emailAddress={{
        // className prop needs to be piped to the root element of this component
        className: props.className,
        onChange: props.onChange,
        name: props.name,
        ref: props.register,
        id: props.id,
      }}
    />
  );
}

export default LandingInput;
