// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4XDKe2Y2CSQJqugRctvMof
// Component: Ct1RIUgXag4lA
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_shared_css from "../shared/plasmic_shared.module.css"; // plasmic-import: mTVXT6w3HHjZ4d74q3gB76/projectcss
import projectcss from "./plasmic_landing_page_4_0_knowledge_management.module.css"; // plasmic-import: 4XDKe2Y2CSQJqugRctvMof/projectcss
import sty from "./PlasmicTestiLink.module.css"; // plasmic-import: Ct1RIUgXag4lA/css

export type PlasmicTestiLink__VariantMembers = {};

export type PlasmicTestiLink__VariantsArgs = {};
type VariantPropType = keyof PlasmicTestiLink__VariantsArgs;
export const PlasmicTestiLink__VariantProps = new Array<VariantPropType>();

export type PlasmicTestiLink__ArgsType = {};
type ArgPropType = keyof PlasmicTestiLink__ArgsType;
export const PlasmicTestiLink__ArgProps = new Array<ArgPropType>();

export type PlasmicTestiLink__OverridesType = {
  root?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultTestiLinkProps {
  className?: string;
}

export const defaultTestiLink__Args: Partial<PlasmicTestiLink__ArgsType> = {};

function PlasmicTestiLink__RenderFunc(props: {
  variants: PlasmicTestiLink__VariantsArgs;
  args: PlasmicTestiLink__ArgsType;
  overrides: PlasmicTestiLink__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultTestiLink__Args, props.args);
  const $props = args;

  return (
    <p.PlasmicLink
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.a,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_shared_css.plasmic_tokens,
        sty.root
      )}
      component={Link}
      platform={"nextjs"}
    >
      {"Enter some text"}
    </p.PlasmicLink>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"],
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTestiLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTestiLink__VariantsArgs;
    args?: PlasmicTestiLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTestiLink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTestiLink__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTestiLink__ArgProps,
      internalVariantPropNames: PlasmicTestiLink__VariantProps,
    });

    return PlasmicTestiLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestiLink";
  } else {
    func.displayName = `PlasmicTestiLink.${nodeName}`;
  }
  return func;
}

export const PlasmicTestiLink = Object.assign(
  // Top-level PlasmicTestiLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTestiLink
    internalVariantProps: PlasmicTestiLink__VariantProps,
    internalArgProps: PlasmicTestiLink__ArgProps,
  }
);

export default PlasmicTestiLink;
/* prettier-ignore-end */
